<a href="https://colab.research.google.com/github/proditor002/Multivariate/blob/main/homeworkinclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np



In [8]:
M1 = np.array([[3, 1, 6], [7, 4, 5], [2, -7, 1]])
print(M1)

[[ 3  1  6]
 [ 7  4  5]
 [ 2 -7  1]]
